apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqtriggers.kubeless-rabbitmq.io
spec:
  group: kubeless-rabbitmq.io
  names:
    kind: RabbitMQTrigger
    plural: rabbitmqtriggers
    singular: rabbitmqtrigger
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                function:
                  description: Subject kubeless function name
                  type: string
                  pattern: "^[a-z0-9]+(-[a-z0-9]+)*$"
                topic:
                  description: RabbitMQ topic name for event-based invocations
                  type: string
                  pattern: "^[a-z0-9]+(-[a-z0-9]+)*$"
              required: ["function", "topic"]
          required: ["spec"]
