apiVersion: kubeless.io/v1beta1
kind: RabbitMQTrigger
metadata:
  labels:
    created-by: kubeless
  name: order-handler
  namespace: default
spec:
  functionSelector:
    matchLabels:
      created-by: kubeless
      function: order-handler
  topic: order